getsentry/sentry-protos

.craft.yml, .github/workflows/build.yml, .github/workflows/release.yml
With this I was able to get release branches pushed from my local machine to GitHub.The `release.yml` workflow can be used to manually create releases as required. Part of the prepare-release action is to prepare and push a release branch.  Once a release branch is pushed the `build.yml` workflow should create artifacts, that can be published.
I'm going to start with python wheels. I'll add rust crates once python wheels are working.
=> Start putting together python packaging with craft

Cargo.lock, rustgenerator/Cargo.toml, rustgenerator/src/main.rs
- Fix the issue with generated `options` module that doesn't include all of the structs.
- Fix non `v1` module names being generated incorrectly.
=> Fix rust packages

proto/sentry_protos/snuba/v1alpha/endpoint_aggregate_bucket.proto, proto/sentry_protos/snuba/v1alpha/endpoint_span_samples.proto, proto/sentry_protos/snuba/v1alpha/trace_item_attribute.proto
There is a requirement to have the ability to search by virtual columns. Remove the AttributeKeyTransformContext which special cased proejct id and make it generic for any desired virtual column
=> feat(eap): add support for virtual columns in the protobuf

proto/sentry_protos/snuba/v1alpha/endpoint_span_samples.proto
forgot to pluralize a repeated field, this makes things confusing
=> fix(eap): pluralize virtual column contexts

proto/sentry_protos/snuba/v1alpha/endpoint_tags_list.proto, proto/sentry_protos/snuba/v1alpha/request_common.proto
1. Add a type argument to the tags endpoint
2. Rename according to EAP terminology
3. Add `trace_item_name` to request payload (in the current case it's `eap_spans`)
4. Add endpoint for attrivute values given specific key
=> feat(eap): separate value types in endpoint

.github/workflows/docs.yml, .gitignore, Makefile, docs/sabledocs.toml
Publish simple generated documentation on each release. The docs are a bit sparse right now, but we can use markdown in comment blocks for messages/services to improve the documentation.
=> feat: Publish documentation on each release

.github/workflows/docs.yml
I missed that sabledocs requires python 3.11
=> fix(docs) Update python used to build docs

Cargo.lock, proto/sentry_protos/snuba/v1/endpoint_find_traces.proto, proto/sentry_protos/snuba/v1/examples.py, proto/sentry_protos/snuba/v1/request_common.proto, proto/sentry_protos/snuba/v1/trace_item_filter.proto
This endpoint allows finding traces that contain events with specific attributes.
The TraceFilter and TraceItemFilter can be combined to search using multiple events,
and multiple attributes on each event.
=> feat(eap): Add an endpoint to find traces

proto/sentry_protos/snuba/v1/endpoint_time_series.proto, proto/sentry_protos/snuba/v1/endpoint_trace_item_attributes.proto, proto/sentry_protos/snuba/v1/endpoint_trace_item_table.proto, proto/sentry_protos/snuba/v1/request_common.proto
Add QueryStats and QueryMetadata to API endpoints response
- Update proto/sentry_protos/snuba/v1/endpoint_trace_item_table.proto
to include optional QueryStats and QueryMetadata fields in
TraceItemTableResponse
- Modify proto/sentry_protos/snuba/v1/request_common.proto
to define QueryStats and QueryMetadata message structures
These changes allow for more detailed query execution information
to be included in responses, enhancing observability and debugging capabilities.
=> Add QueryStats and QueryMetadata to TraceItemTableResponse

proto/sentry_protos/snuba/v1/request_common.proto
This commit introduces trace logging functionality:
- Added `trace_log` string field to ResponseMeta
These changes allow clients to request trace logging for their queries and receive the clickhouse trace logs in the response. This feature will help with debugging and performance analysis of EAP API.
=> Add trace logging support to ResponseMeta

proto/sentry_protos/snuba/v1/endpoint_trace_item_attributes.proto
Instead of using the `name` field which is a raw string, since we're looking values of a specific attribute, use the attribute key instead.
=> Use AttributeKey in TraceItemAttributeValuesRequest

proto/sentry_protos/snuba/v1/endpoint_trace_item_attributes.proto
Changes
* added response metadata to TraceItemAttributeNamesResponse. this can be used to provide metadata back to the user.
* deprecated offset in the Request and replaced it with a page tokens, this aligns with how it is done in the other endpoints.
* added some more comments
=> feat: TraceItemAttributeNames, add response metadata to Response, add page tokens

proto/sentry_protos/sentry/v1/taskworker.proto
Add proto definitions for the ConsumerService as well as protos for the messages used
to interact with that service.
Add a common error structure for returning errors.
The service currently has support for GetTask and SetTaskStatus, which is what the workers
will use to fetch new tasks and update the task statuses after a task is finished.
=> feat(tasks): Add protos for the ConsumerService

.github/workflows/ci.yml, Makefile, py/tests/test_snuba_v1.py, py/tests/test_taskworker_v1.py, requirements.txt
- Move examples into py/tests so that we can run them.
- Fix broken examples in snuba module.
- Add tests for taskworker protos
- Extend CI configuration to run python tests on generated code.
Refs #42
=> feat: Run examples as tests and add tests for taskworker

proto/sentry_protos/snuba/v1/endpoint_time_series.proto, proto/sentry_protos/snuba/v1/endpoint_trace_item_table.proto, proto/sentry_protos/snuba/v1/trace_item_attribute.proto
Adding a reliability enum to allow us to extend the reliability states in the future
=> Use a reliability enum instead of boolean

proto/sentry_protos/sentry/v1/taskworker.proto
Some tasks can be marked as being only executed at most once. Add a flag to denote that status.
Tasks with this status are guaranteed to execute 0 or 1 times. The worker uses this flag to
determine how it should handle the task.
=> ref(taskbroker) Add at_most_once flag to task activations

proto/sentry_protos/sentry/v1/taskworker.proto
In order for taskbroker to return tasks specific to namespace (e.g. symbolicator use-case), it needs to be able to receive a namespace as part of the gRPC request object.
=> feat(taskbroker): Add namespace parameter to get/set requests

proto/sentry_protos/sentry/v1/taskworker.proto
Enrich `fetch_next` type. By doing this, we would not run into the case where`fetch_next: bool` is not provided (or set to false) and `fetch_next_namespace: string` is provided. Now, either the fetch_next message is provided with an optional namespace, or not at all.
=> feat(taskbroker): Improve fetch_next

.github/workflows/ci.yml
The buf-breaking action is deprecated and this moves us to the replacement. One benefit of the unified action is that it leaves PR comments for results.
=> chore: Update to buf-action

Makefile
I tried to run `make docs` locally but it failed bc i didnt have `protoc` installed. I added a target to the makefile that installs `protoc` if not installed. Now if you run `make docs` and dont have `protoc` installed, it installs it for you.
=> feat: add ensure-protoc to makefile

proto/sentry_protos/snuba/v1/endpoint_find_traces.proto, proto/sentry_protos/snuba/v1/endpoint_get_traces.proto
This will add Protobuf files describing a new endpoint to find traces. It will return a list of traces with fields requested.
Features:
- You can pick which fields from the `enum`
- You can specify the type you want from a field
- You can use the same filter conditions as for the `TraceItemTable` endpoint
- You can order by any field from the `enum`
Limitations:
- No aggregation possible
- No support for alias
- A fixed list of fields to query
Since traces are not a defined object but a specific view on an aggregated list of spans, I don't think we should plan to support any field possible. Maybe at some point, we'll make the trace a real object and we'll add trace attributes and by then, we can design a new version of the endpoint.
Closes …
=> feat(eap): Add a GetTraces endpoint

.pre-commit-config.yaml
currently we can do local git commits to `main` branch. this pr adds a pre-commit hook so we cant anymore.
idk if theres any branch protections on the remote repo
=> feat: no local commits to main branch

.pre-commit-config.yaml
for some reason my last pr https://github.com/getsentry/sentry-protos/pull/77
prevented committing to any branch not just main. IDK why but im rolling it back bc of that.
=> bug: cant commit to any branch locally

proto/sentry_protos/snuba/v1/endpoint_trace_item_table.proto, proto/sentry_protos/snuba/v1/trace_item_filter.proto, py/tests/test_snuba_v1.py
Adding an aggregation filter to allow queries with a having clause in order to support https://github.com/getsentry/eap-planning/issues/143
A trace item table request with an aggregation filter could look something like this:
```
{
"meta": {
},
"columns": [
{
"key": {
"type": "TYPE_STRING",
"name": "sentry.browser.name"
},
"label": "browser.name"
},
{
"aggregation": {
"aggregate": "FUNCTION_AVG",
"key": {
"type": "TYPE_FLOAT",
"name": "sentry.duration"
},
"label": "avg(duration)",
"extrapolation_mode": "EXTRAPOLATION_MODE_SAMPLE_WEIGHTED"
},
"label": "avg(duration)"
}
],
"order_by": [
{
"column": {
"aggregation": {
"aggregate": "FUNCTION_AVG",
"key": {
"type": "TYPE_FLOAT",
"name": "sentry.duration"
},
"label": "avg(duration)",
"extrapolation_mode": "EXTRAPOLATION_MODE_SAMPLE_WEIGHTED"
} …
```
=> feat(eap): Add aggregation filter

proto/sentry_protos/snuba/v1/trace_item_attribute.proto
Python floats are 64 bits, and when we store them into [Protobuf floats (which are 32 bits)](https://protobuf.dev/programming-guides/proto3/#scalar), they get downcasted. This results in inaccuracy upon retrieval.
This is how I found out Python floats are indeed 64 bits.
https://docs.python.org/3/library/sys.html#sys.float_info
log_base_2(max_exp) + mant_dig + 1 (for sign) = 10 + 53 + 1 = 64
- log_base_2(max_exp): number of digits used to represent the exponent field
- mant_dig: number of digits in significand or mantissa
- 1: sign bit
=> fix(eap-api): Use `doubles` instead of `floats`

proto/sentry_protos/snuba/v1/trace_item_attribute.proto
https://github.com/getsentry/eap-planning/issues/146
Does https://github.com/getsentry/sentry-protos/pull/84 for arrays as well
=> fix(eap-api): Use doubles arrays instead of floats arrays

py/tests/test_snuba_v1.py
https://github.com/getsentry/eap-planning/issues/146
=> fix(eap-api): update tests to use doubles instead of floats

proto/sentry_protos/snuba/v1/trace_item_attribute.proto
Adding `TYPE_DOUBLE` is purely cosmetic and should not have been added
=> fix(eap-api): deprecate TYPE_DOUBLE

proto/sentry_protos/snuba/v1/endpoint_trace_item_table.proto, proto/sentry_protos/snuba/v1/trace_item_attribute.proto
This is used to distinguish between fields that are default values (e.g. 0 and empty string) and fields that are null (e.g. when aggregating over an empty set).
The two approaches I thought of were:
1. add an array to represent if the result is null for each column (first commit)
2. add a bool value to the AttributeValue to represent nullity (most recent commit)
Since the first approach would increase the message size, I prefer the second approach which doesn't affect the message size.
=> feat(eap): Add an is_null field for to AttributeValue

proto/sentry_protos/snuba/v1/endpoint_time_series.proto, proto/sentry_protos/snuba/v1/endpoint_trace_item_table.proto
Are we reimplementing snql? Who knows, but I am certainly reimplementing the grammar of a query language.
This allows `add`, `subtract`, `multiply`, and `divide` to be specified as operations in the "select" of timeseries endpoint and traceitemtable
The reason I nested `BinaryFormula` inside of `message Column` instead of making it separate is bc of the imports between timeseries and traceitemtable. It wouldnt let me name both messages `BinaryFormula` since it would be a duplicate object defined twice.
=> feat: formulas in timeseries and traceitemtable endpoints

proto/sentry_protos/snuba/v1/trace_item_attribute.proto
Deprecating the old `val_null` field as we have an `is_null` bool now.
=> fix(eap): deprecate val_null field

Cargo.lock, proto/sentry_protos/snuba/v1/endpoint_trace_item_details.proto, py/tests/test_snuba_v1.py
This lets you do the equivalent of `SELECT * FROM trace_items WHERE item_type=log AND item_id=12345`
=> feat: Add a "trace item details" endpoint to get everything for a single item

proto/sentry_protos/snuba/v1/downsampled_storage.proto, proto/sentry_protos/snuba/v1/request_common.proto
This PR enables users to specify the mode to interact with the downsampled storages and receive (as part of the request) metadata about the downsampled storages.
These API changes are necessary to address https://github.com/getsentry/eap-planning/issues/212 (for now, we are skipping over the additional mode (lower priority) where client (sentry) makes a request with its own rows scanned and timeout limit)
=> feat(sampling-in-storage): api changes

proto/sentry_protos/snuba/v1/endpoint_trace_item_details.proto
EAP is organized around traces and so it makes sense that to find a specific item, you would need a trace id as well. 
Practically, this makes it so that the indexing on `trace_id` is used for this lookup. Technically this can be facilitated through the optional `TraceItemFilter` that is on the message, however this makes it more clear to the user that `trace_id` is necessary for lookup
=> Make trace_id a first class field in TraceItemDetails

proto/sentry_protos/snuba/v1/endpoint_time_series.proto, proto/sentry_protos/snuba/v1/endpoint_trace_item_table.proto, py/tests/test_snuba_v1.py
this allows user to specify default values for formulas in the traceitemtable and timeseries endpoints.
still needs support for it to be implemented in snuba.
it is for this ticket
https://github.com/orgs/getsentry/projects/284/views/1?pane=issue&itemId=104071496&issue=getsentry%7Ceap-planning%7C232
=> feat: default value for formulas

proto/sentry_protos/snuba/v1/downsampled_storage.proto
We no longer want to expose the specific tiers. Instead, we just inform the user if there exists a higher accuracy tier that this query could route to. Note that if this query actually goes to a higher accuracy tier, it could time out. But we're not considering that.
=> feat(storage-routing): indicate if there is a higher accuracy tier

proto/sentry_protos/sentry/v1/taskworker.proto
We aren't using these, as we're using the protos in taskbroker.v1 instead.
=> chore(taskbroker) Deprecate unused messages and grpc

requirements.txt
this is to patch a security vulnerability, its a follow up to [this](https://github.com/getsentry/snuba/pull/7290)
=> chore: upgrade protobuf dependency version

proto/sentry_protos/snuba/v1/trace_item_attribute.proto, rust/src/sentry_protos.snuba.v1.rs
Someone asked why this was deprecated / what the alternative was. Let's make it explicitly clear what to use instead
=> Clarify alternative to `FUNCTION_AVERAGE`

CODEOWNERS, proto/sentry_protos/snuba/v1/trace_item.proto, rust/src/sentry_protos.snuba.v1.rs
This PR allows us to pass a different value for retention of the downsampled datasets.
=> feat(eap): Allow to pass a different retention for downsampled data

proto/sentry_protos/snuba/v1/endpoint_time_series.proto, proto/sentry_protos/snuba/v1/endpoint_trace_item_table.proto, proto/sentry_protos/snuba/v1/request_common.proto, py/tests/test_snuba_v1.py, rust/src/sentry_protos.snuba.v1.rs
Adding trace item filters with type for cross item query support
=> feat(cross-item-queries): Add trace item filters with type in trace item table and time series endpoints

README.md
Cleaning up some spurious spaces and fixed the use of multiple top-level headings, moving each existing heading down one level.
=> chore(readme): Cleaning up the readme
